version: "3.8"
services:
  database:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_DB=metadata
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=clave
      - PGHOST=localhost
    ports:
      - "5432:5432"
    #network_mode: bridge
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data:
    external: true